export const issueOptions = {
    "Road & Transportation": [
        "Potholes",
        "Broken road surface",
        "Damaged speed bumps",
        "Missing or broken road signs",
        "Faded lane markings",
        "Damaged footpath / sidewalk",
        "Broken or missing street lights",
        "Illegal parking",
    ],
    "Bridges & Structures": [
        "Bridge cracks or damage",
        "Broken railing",
        "Structural instability",
        "Water leakage or erosion around supports",
    ],
    "Garbage & Sanitation": [
        "Overflowing garbage bins",
        "Illegal dumping",
        "Uncollected garbage",
        "Dead animal removal",
        "Open drains",
        "Sewage leaks",
    ],
    "Water Supply": [
        "Broken water pipeline",
        "Water contamination",
        "Low water pressure",
        "Water leakage in public areas",
    ],
    "Electricity & Lighting": [
        "Street lights not working",
        "Dangling wires",
        "Broken electrical poles",
        "Frequent power cuts",
    ],
    "Environment & Green Spaces": [
        "Fallen trees",
        "Tree trimming required",
        "Damaged public parks",
        "Unauthorized tree cutting",
    ],
    "Public Health": [
        "Mosquito breeding sites",
        "Open stagnant water",
        "Animal menace (stray dogs, monkeys)",
        "Public toilets not maintained",
    ],
    "Public Facilities": [
        "Damaged bus shelters",
        "Broken benches",
        "Public drinking water issues",
        "Broken playground equipment",
    ],
    "Building & Construction": [
        "Unauthorized construction",
        "Unsafe abandoned buildings",
        "Construction debris on road",
    ],
    "Traffic & Safety": [
        "Traffic signals not working",
        "Obstructed crosswalk",
        "Illegal encroachment on roads",
        "Blinking / faulty signals",
    ],
};
